/*
 * This file is generated by jOOQ.
 */
package io.kcache.rdbms.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import io.kcache.rdbms.jooq.tables.Kv;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kcache extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kcache</code>
     */
    public static final Kcache KCACHE = new Kcache();

    /**
     * The table <code>kcache.KV</code>.
     */
    public final Kv KV = Kv.KV;

    /**
     * No further instances allowed
     */
    private Kcache() {
        super("kcache", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Kv.KV);
    }
}
