/*
 * This file is generated by jOOQ.
 */
package io.kcache.rdbms.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import io.kcache.rdbms.jooq.tables.Kv;
import io.kcache.rdbms.jooq.tables.records.KvRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * kcache.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<KvRecord> KEY_KV_PRIMARY = Internal.createUniqueKey(Kv.KV, DSL.name("KEY_KV_PRIMARY"), new TableField[] { Kv.KV.KV_KEY }, true);
}
