/*
 * This file is generated by jOOQ.
 */
package io.kcache.rdbms.jooq;


import io.kcache.rdbms.jooq.tables.Kv;


/**
 * Convenience access to all tables in kcache.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kcache.KV</code>.
     */
    public static final Kv KV = Kv.KV;
}
